implemented add tasks, remove tasks and filter tasks by state
echnaya-p/todo-react pull request #3
Opened 2021-03-16 20:36 UTC by echnaya-p

implemented add tasks, remove tasks and filter tasks by state (active and finished)

2021-03-16 20:51 UTC, w3lld1 requested changes
нужно добавить propTypes каждому компоненту и описать там все пропсы и их типы

2021-03-16 20:51 UTC, w3lld1 commented on src/App.css
>  .App-header {
этот стиль нужен? используется в проекте? Остальные тоже проверь

2021-03-16 20:51 UTC, w3lld1 commented on src/Form.js
> +import {taskState} from "./constants/constants";
строкой выше с пробелами, а тут нет. Приведи к единому стилю. Посмотри по всем файлам

2021-03-16 20:51 UTC, w3lld1 commented on src/Form.js
> +    const handleAdd = () => {
слипшийся код в этой функции, разбей пустыми строками на блоки для читаемости

2021-03-16 20:51 UTC, w3lld1 commented on src/Tasks.js
> +    const handleChangeState = (id) => () => {
слипшийся код, функции отделяй пустой строкой

2021-03-16 20:51 UTC, w3lld1 commented on src/ToDo.js
> +    const [select, setSelect] = useState('all');
везде с пробелами, тут нет. приведи к общему виду

2021-03-16 20:51 UTC, w3lld1 commented on src/ToDo.js
> +
лишняя пустая строка

2021-03-16 20:51 UTC, w3lld1 commented on src/ToDo.js
> +            <Filter
есть ощущение, что переданные пропсы в Filter не совпадают с теми, которые ты внутри Filter берешь из пропсов. Проверь

2021-03-17 18:25 UTC, echnaya-p commented
> нужно добавить propTypes каждому компоненту и описать там все пропсы и их типы

сделано

2021-03-17 18:25 UTC, echnaya-p commented on src/ToDo.js
> +            <Filter
перепроверила, удалила лишнее

2021-03-17 18:25 UTC, echnaya-p commented on src/ToDo.js
> +
удалила

2021-03-17 18:26 UTC, echnaya-p commented on src/ToDo.js
> +    const [select, setSelect] = useState('all');
сделано

2021-03-17 18:26 UTC, echnaya-p commented on src/Tasks.js
> +    const handleChangeState = (id) => () => {
отделила

2021-03-17 18:26 UTC, echnaya-p commented on src/Form.js
> +    const handleAdd = () => {
сделала

2021-03-17 18:26 UTC, echnaya-p commented on src/Form.js
> +import {taskState} from "./constants/constants";
привела

2021-03-17 18:26 UTC, echnaya-p commented on src/App.css
>  .App-header {
удалила все лишнее

2021-03-17 18:56 UTC, w3lld1 commented on src/Filter.js
> +import * as PropTypes from 'prop-types';
почему такой импорт? обычный import PropTypes from 'prop-types' не работает?

2021-03-17 18:56 UTC, w3lld1 commented on src/Form.js
>      const handleAdd = () => {
handleAdd что? что добавляется? из названия метода непонятно

2021-03-17 18:56 UTC, w3lld1 commented on src/Form.js
> +    const handleChange = (e) => {
тоже самое, Change что? непонятно, что делает обработчик

2021-03-17 18:56 UTC, w3lld1 commented on src/Form.js
>          onUpdateIds([ id, ...ids ]);
может все функции on... сгруппировать вместе? эту перенести ниже к остальным? или логика меняется от этого?

2021-03-17 18:57 UTC, echnaya-p commented on src/Filter.js
> +import * as PropTypes from 'prop-types';
нет

2021-03-17 18:59 UTC, echnaya-p commented on src/Form.js
>      const handleAdd = () => {
исправила на handleAddTask

2021-03-17 19:01 UTC, echnaya-p commented on src/Form.js
>          onUpdateIds([ id, ...ids ]);
перенесла

2021-03-17 19:04 UTC, w3lld1 commented on src/Filter.js
> +        if (event.target.value !== 'all') {
блоки if желательно тоже отделять пустой строкой

2021-03-17 19:04 UTC, w3lld1 commented on src/Tasks.js
> +    const handleDelete = (id) => () => {
слипшийся код

2021-03-17 19:11 UTC, w3lld1 commented on src/Tasks.js
> +    const handleDelete = (id) => () => {
плюс опять же delete что?

2021-03-17 19:13 UTC, echnaya-p commented on src/Form.js
> +    const handleChange = (e) => {
исправила на handleChangeText

2021-03-17 19:13 UTC, echnaya-p commented on src/Filter.js
> +        if (event.target.value !== 'all') {
отделила

2021-03-17 19:21 UTC, w3lld1 approved these changes

2021-03-17 19:23 UTC, merged